### PR TITLE
Support speech synthesis tasks

### PR DESCRIPTION
**Pull request by lawitschka**
This commit introduces creating and retrieving asynchronous speech
synthesis tasks that store the resulting audio file in an S3 bucket.

### CODE REVIEW

**Comment by josephan** [comment]
LGTM 👍

**Comment by josephan** [comment]
@lawitschka would you be interested in being the new owner of this package on hex.pm and publish a new release?

**Comment by lawitschka** [comment]
@josephan Sure, happy to take it over because we will be using it now

You are going to find me here on Hex https://hex.pm/users/lawitschka

**Comment by josephan** [comment]
@lawitschka Done! Thank you!

**Pull request merged**
